name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-test:
    name: Compile and test application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set  up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Grandexecutive permissionfor gradlew
        run: chmod +x ./gradlew
        
      - name: Gradlew clean
        run: ./gradlew clean 

      - name: Gradlew test run
        id: test
        run: ./gradlew test

